[package]
name = "zonkey"
version = "0.1.0"
edition = "2021"
description = "CLI Interpreter for the Zonkey programming language"
authors = ["Sam Bowden"]

[dependencies]
interpreter = { path = "../interpreter" }
termcolor = "1.1"
unicode-segmentation = "1.10.0"
