[package]
name = "zonkey-browser"
version = "0.1.0"
edition = "2021"
description = "Browser that run programs written in Zonkey script over the internet"
authors = ["Sam Bowden"]

[dependencies]
iced = { version = "0.8", features = ["svg", "image"] }
iced_native = "0.9.1"
tab = { path = "../tab" }
