[workspace]

members = [
	"interpreter",
	"zonkey-browser",
	"zonkey",
]

resolver = "2"

[profile.release]
strip = true
lto = true
opt-level = 3
panic = "abort"
codegen-units = 1

[profile.no-debug-info]
inherits = "dev"
debug-assertions = false
