[package]
name = "resource-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "4.0.1"
reqwest = { version = "0.11", features = ["blocking"] }
iced = { version = "0.8", features = ["svg", "image"] }
iced_native = "0.9.1"
